<<<<<<< Updated upstream
google_api_key = "AIzaSyC-C1avZpPvUMzmtZlVwmaPQUm9kYeNPOg"
=======
#.streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyD-yfyYNcanhRD99QdEBuR-u7nmr3mPyrY"
>>>>>>> Stashed changes
